version: '3'
services:

  ikev2-vpn:
    container_name: ikev2
    image: notthebee/ikev2
    ports:
      - 5558:4500/udp
      - 5559:500/udp
      - 5557:80/tcp 
      # Only needed during the first run for Let's Encrypt 
      # certificates, feel free to remove it afterwards
    privileged: yes
    volumes:
      - /docker-persistent-data/ikev2/config:/config
      - /docker-persistent-data/ikev2/letsencrypt:/etc/letsencrypt
    environment:
      - DNS_SERVERS="223.5.5.5, 223.6.6.6"
      - VPNHOST=www.350886.fun
      - EMAILADDR=350886@qq.com
      - VPNUSERNAME=guo
      - VPNPASSWORD=Huang*/881628
      # Pick one of the following if you want the VPN
      # to connect automatically on certain WiFi networks
      - INCLUDE_SSIDS="SSID1, SSID2"
      # or to connect on all WiFi networks except for these
      - EXCLUDE_SSIDS="SSID1, SSID2"
      # ...or nothing at all
